config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls', namespace='ecommerce')),
    path('user/', include('user.urls', namespace='user')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce'


urlpatterns = [
    path('', views.index, name='index'),
    path('products/detail/<slug:slug>/', views.product_detail, name='product-detail'),
    path('create-product/', views.product_create, name='product_create'),
    path('delete-product/<slug:slug>/', views.product_delete, name='product_delete'),
    path('edit-product/<slug:slug>/', views.product_edit, name='product_edit'),
    path('customers/', views.customers, name='customers'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/details/', views.customer_details, name='customer-detail'),
    path('product/like/<slug:slug>/', views.product_like_view, name='product-like'),
    path('product/comment/send/<slug:slug>/', views.send_product_comment, name='product-comment'),
    path('search/', views.search_view, name='search'),
    path('export-data/', views.export_data, name='export_data')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'


urlpatterns = [
    path('login-oauth-page/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('register/', views.register_page, name='register_page'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('verify-email/complete/', views.verify_email_complete, name='verify-email-complete'),
]

ecommerce/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal
from phonenumber_field.modelfields import PhoneNumberField
from django.template.defaultfilters import slugify

import user

# Create your models here.


STOCK_STATUS = (
    ('available', 'Available'),
    ('sold_out', 'Sold-Out')
)

class Product(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products/images')
    information = models.TextField()
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    discount = models.PositiveIntegerField(default=0)
    shipping_cost = models.DecimalField(max_digits=9, decimal_places=2)
    stock = models.CharField(max_length=200, choices=STOCK_STATUS, default='available')
    favorite = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_products')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products', null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    @property
    def get_absolute_url(self):
        return self.image.url

    @property
    def get_price(self):
        if self.discount:
            return (self.price * Decimal(1 - self.discount / 100)).quantize(Decimal('0.01'))
        return self.price

    @property
    def rating(self):
        comments = self.comments.all()
        if comments:
            total_rating = (sum([comment.rating for comment in comments]) / self.comments.count()).quantize(Decimal('0.1'))
            return total_rating
        return 5.0

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Attribute(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class AttributeValue(models.Model):
    value = models.CharField(max_length=100)

    def __str__(self):
        return self.value


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='product_attributes', null=True, blank=True)
    attribute = models.ForeignKey(Attribute, on_delete=models.SET_NULL, null=True, blank=True)
    attribute_value = models.ForeignKey(AttributeValue, on_delete=models.SET_NULL, null= True, blank=True)






class ProductComment(models.Model):
    rating = models.DecimalField(validators=[MinValueValidator(0.5), MaxValueValidator(5.0)], max_digits=2, decimal_places=1)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}: {self.comment}"


class Customers(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = PhoneNumberField(region="UZ")
    billing_address = models.CharField(max_length=255)
    joined = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

ecommerce/forms.py
from django import forms

from .models import ProductComment, Product, Customers


class ProductCommentForm(forms.ModelForm):

    class Meta:
        model = ProductComment
        fields = ['rating', 'name', 'email', 'comment']
        widgets = {
            'rating': forms.NumberInput(attrs={'step': '0.5', 'min': '0', 'max': '5'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = Customers
        fields = '__all__'

ecommerce/views.py
import csv
import json
import openpyxl
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.context_processors import request

from ecommerce.forms import ProductCommentForm, ProductModelForm
from ecommerce.models import Product, ProductAttribute, Customers


# Create your views here.


def index(request):
    products = Product.objects.all()
    product_attributes = ProductAttribute.objects.all()

    products = Product.objects.all().order_by('id')
    paginator = Paginator(products, 5)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'ecommerce/product-list.html', context=context)

    # paginator = Paginator(products, 4)
    # page_number = request.GET.get("page")
    # page_obj = paginator,get_page(page_number)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    context = {
        'product': product
    }

    return render(request, 'ecommerce/product-details.html', context=context)

def customers(request):
    return render(request, 'ecommerce/customers.html')

def customer_details(request):
    return render(request, 'ecommerce/customer-details.html')


@login_required
def product_like_view(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.user in product.likes.all():
        product.likes.remove(request.user)
    else:
        product.likes.add(request.user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def send_product_comment(request, slug):
    product = get_object_or_404(Product, slug=slug)

    if request.method == 'POST':
        comment_form = ProductCommentForm(data=request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.product = product
            comment.rating = Decimal(request.POST.get('rating', 0))
            comment.save()
            return redirect('ecommerce:product-detail', pk=product.pk)

    else:
        comment_form = ProductCommentForm()

    context = {
        'product': product,
        'comment_form': comment_form
    }

    return render(request, 'ecommerce/product-details.html', context=context)


def product_create(request):
    # form = ProductModelForm()
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('ecommerce:index')
    else:
        form = ProductModelForm()
    context = {
        'form': form,
        'action': 'Create'
    }
    return render(request, 'ecommerce/create.html', context=context)


def product_delete(request, slug):
    try:
        product = Product.objects.get(slug=slug)
        product.delete()
        return redirect('index')
    except Product.DoesNotExist as e:
        print(e)


def product_edit(request, slug):
    product = Product.objects.get(slug=slug)
    form = ProductModelForm(instance=product)
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('ecommerce:product-detail', slug=product.slug)
    context = {
        'form': form,
        'product': product,
        'action': 'Edit New'
    }
    return render(request, 'ecommerce/create.html', context=context)


def search_view(request):
    search_query = request.GET.get('q', '')
    products = Product.objects.filter(name__icontains=search_query)
    context = {
        'products': products
    }
    return render(request, 'ecommerce/product-list.html', context=context)



def customer_list(request):
    customers = Customers.objects.all()
    context = {
        'customers': customers
    }
    return render(request, 'ecommerce/customers.html', context=context)


def export_data(request):
    format = request.GET.get('format', '')
    response = None
    if format == 'csv':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename=customer_list.csv'
        writer = csv.writer(response)
        writer.writerow(['Id', 'Full Name', 'Email', 'Phone Number', 'Address', 'Joined'])

        for customer in Customers.objects.all():
            writer.writerow([customer.id, customer.name, customer.email, str(customer.phone), customer.billing_address, customer.joined.strftime("%Y-%m-%d")])

    elif format == 'json':
        response = HttpResponse(content_type='application/json')
        customers = Customers.objects.all()
        data = []
        for customer in customers:
            data.append({
                "name": customer.name,
                "email": customer.email,
                "phone": str(customer.phone),
                "billing_address": customer.billing_address,
                "joined": customer.joined.strftime("%Y-%m-%d")
            })

        response.write(json.dumps(data, indent=3))
        response['Content-Disposition'] = 'attachment; filename=customers.json'

    elif format == 'xlsx':
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename=customers.xlsx'

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Customers"

        headers = ['Id', 'Full Name', 'Email', 'Phone Number', 'Address', 'Joined']
        ws.append(headers)

        for customer in Customers.objects.all():
            ws.append([customer.id, customer.name, customer.email, str(customer.phone), customer.billing_address, customer.joined.strftime("%Y-%m-%d")])

        wb.save(response)

    else:
        response = HttpResponse(status=400)
        response.content = 'Bad request'

    return response

ecommerce/templates/ecommerce/product-details.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <main class="main" id="top">
        <div class="content">
          <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6 mb-4 mb-lg-0">
                  <div class="product-slider" id="galleryTop">
                    <div class="swiper-container theme-slider position-lg-absolute all-0" data-swiper='{"autoHeight":true,"spaceBetween":5,"loop":true,"loopedSlides":5,"thumb":{"spaceBetween":5,"slidesPerView":5,"loop":true,"freeMode":true,"grabCursor":true,"loopedSlides":5,"centeredSlides":true,"slideToClickedSlide":true,"watchSlidesVisibility":true,"watchSlidesProgress":true,"parent":"#galleryTop"},"slideToClickedSlide":true}'>
                      <div class="swiper-wrapper h-100">

                        <div class="swiper-slide h-100"><img class="rounded-1 fit-cover h-100 w-100" src="{{ product.get_absolute_url }}" alt="" /></div>

                      </div>
                      <div class="swiper-nav">
                        <div class="swiper-button-next swiper-button-white"></div>
                        <div class="swiper-button-prev swiper-button-white"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6">
                  <h5>{{ product.name }}</h5>
                  <div class="fs--2 mb-3 d-inline-block text-decoration-none">
                    <span class="fa fa-star text-warning"></span>
                    <span class="fa fa-star text-warning"></span>
                    <span class="fa fa-star text-warning"></span>
                    <span class="fa fa-star text-warning"></span>
                    <span class="fa fa-star-half-alt text-warning star-icon"></span>
                    <span class="ms-1 text-600">{{ product.comment.count }}</span>
                  <p class="fs--1">{{ product.information }}</p>

                  <h4 class="d-flex align-items-center"><span class="text-warning me-2">${{ product.get_price }}</span><span class="me-1 fs--1 text-500">

                        <del class="me-1">${{ product.price }}</del><strong>-{{ product.discount }}%</strong></span></h4>

                  <p class="fs--1 mb-1"> <span>Shipping Cost: </span><strong>${{ product.shipping_cost }}</strong></p>
                  <p class="fs--1">Stock: <strong class="text-success">{{ product.stock }}</strong></p>
                  <p class="fs--1 mb-3">Tags:

                    <a class="ms-2" href="#!">{{ product.category.name }}</a>

                  </p>
                  <div class="row">
                    <div class="d-flex align-items-center gap-1">
                      <div class="col-auto pe-0">
                      <div class="input-group input-group-sm" data-quantity="data-quantity">
                        <button class="btn btn-sm btn-outline-secondary border-300" data-field="input-quantity" data-type="minus">-</button>
                        <input class="form-control text-center input-quantity input-spin-none" type="number" min="0" value="0" aria-label="Amount (to the nearest dollar)" style="max-width: 50px" />
                        <button class="btn btn-sm btn-outline-secondary border-300" data-field="input-quantity" data-type="plus">+</button>
                      </div>
                    </div>
                      <div class="col-auto px-2 px-md-3"><a class="btn btn-sm btn-primary" href="#!"><span class="fas fa-cart-plus me-sm-2"></span><span class="d-none d-sm-inline-block">Add To Cart</span></a></div>
                      <div class="col-auto px-0"><a class="btn btn-sm btn-outline-danger border-300" href="{% url 'ecommerce:product-like' product.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Add to Wish List"><span class="far fa-heart me-1"></span>{{ product.likes.count }}</a></div>

                      <div>
                        <form method="POST" action="{% url 'ecommerce:product_delete' product.id %}">
                          <button type="submit" class="btn btn-danger">Delete</button>
                          {% csrf_token %}
                        </form>
                      </div>


                          <button type="submit" class="btn btn-outline-primary">
                            <a href="{% url 'ecommerce:product_edit' product.id %}">Edit</a>
                          </button>

                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="overflow-hidden mt-4">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                      <li class="nav-item"><a class="nav-link active ps-0" id="description-tab" data-bs-toggle="tab" href="#tab-description" role="tab" aria-controls="tab-description" aria-selected="true">Description</a></li>
                      <li class="nav-item"><a class="nav-link px-2 px-md-3" id="specifications-tab" data-bs-toggle="tab" href="#tab-specifications" role="tab" aria-controls="tab-specifications" aria-selected="false">Specifications</a></li>
                      <li class="nav-item"><a class="nav-link px-2 px-md-3" id="reviews-tab" data-bs-toggle="tab" href="#tab-reviews" role="tab" aria-controls="tab-reviews" aria-selected="false">Reviews</a></li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                      <div class="tab-pane fade show active" id="tab-description" role="tabpanel" aria-labelledby="description-tab">
                        <div class="mt-3">

                          <p>{{ product.description }}</p>

                        </div>
                      </div>
                      <div class="tab-pane fade" id="tab-specifications" role="tabpanel" aria-labelledby="specifications-tab">
                        <table class="table fs--1 mt-3">
                          <tbody>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Processor</td>
                              <td>2.3GHz quad-core Intel Core i5,</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Memory</td>
                              <td>8GB of 2133MHz LPDDR3 onboard memory</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Brand Name</td>
                              <td>Apple</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Model</td>
                              <td>Mac Book Pro</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Display</td>
                              <td>13.3-inch (diagonal) LED-backlit display with IPS technology</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Storage</td>
                              <td>512GB SSD</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Graphics</td>
                              <td>Intel Iris Plus Graphics 655</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Weight</td>
                              <td>7.15 pounds</td>
                            </tr>
                            <tr>
                              <td class="bg-100" style="width: 30%;">Finish</td>
                              <td>Silver, Space Gray</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                      <div class="tab-pane fade" id="tab-reviews" role="tabpanel" aria-labelledby="reviews-tab">
                        <div class="row mt-3">
                          <div class="col-lg-6 mb-4 mb-lg-0">
                            {% for comment in product.comments.all %}
                            <div class="mb-1">
                                {% with ''|center:comment.rating as range %}
                                  {% for f in range %}
                                    <span class="fa fa-star text-warning"></span>
          <!--                          <span class="fa fa-star-half-alt text-warning star-icon"></span>-->
                                  {% endfor %}
                              {% endwith %}
                                <span class="ms-3 text-dark fw-semi-bold">Awesome support, great code 😍</span>
                            </div>
                            <p class="fs--1 mb-2 text-600">{{ comment.name }} • {{ comment.created_at }}</p>
                            <p class="mb-0">{{ comment.comment }}</p>
                            {% endfor %}
                          </div>
                          <div class="col-lg-6 ps-lg-5">
                            <form method="POST" action="{% url 'ecommerce:product-comment' product.slug %}">
                              {% csrf_token %}
                              <h5 class="mb-3">Write your Review</h5>
                              <div class="mb-3">
                                <label class="form-label">Ratting: </label>
                                <div id="starRating" data-rater='{"starSize":32,"step":0.5}'></div>
                                <input type="hidden" id="ratingInput" name="rating">
                              </div>
                              <div class="mb-3">
                                <label class="form-label" for="formGroupNameInput">Name:</label>
                                <input class="form-control" id="formGroupNameInput" type="text" name="name"/>
                              </div>
                              <div class="mb-3">
                                <label class="form-label" for="formGroupEmailInput">Email:</label>
                                <input class="form-control" id="formGroupEmailInput" type="email" name="email"/>
                              </div>
                              <div class="mb-3">
                                <label class="form-label" for="formGrouptextareaInput">Review:</label>
                                <textarea class="form-control" id="formGrouptextareaInput" rows="3" name="comment"></textarea>
                              </div>
                              <button class="btn btn-primary" type="submit">Submit</button>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

{% endblock %}

{% block extra_js %}

<script>
  document.addEventListener("DOMContentLoaded", function () {
      var starRating = document.getElementById("starRating");
      var ratingInput = document.getElementById("ratingInput");

      if (starRating && ratingInput) {
          starRating.addEventListener("click", function () {
              var selectedRating = starRating.getAttribute("data-rating");
              if (selectedRating) {
                  ratingInput.value = selectedRating;
              }
          });
      }
  });
</script>

{% endblock %}

ecommerce/templates/ecommerce/product-list.html
{% extends 'base.html' %}

{% block content %}
<div class="card mb-3">
    <div class="card-body">
      <div class="row flex-between-center">


        <div class="col-sm-auto mb-2 mb-sm-0">
          <h6 class="mb-0">Showing {{ products.count }} Products</h6>
        </div>

        <div class="col-sm-auto mb-2 mb-sm-0">
          <a class="btn btn-outline-succes" href="{% url 'ecommerce:product_create'%}"> Add product </a>
        </div>


        <div class="col-sm-auto">
          <div class="row gx-2 align-items-center">
            <div class="col-auto">
              <form class="row gx-2">
                <div class="col-auto"><small>Sort by: </small></div>
                <div class="col-auto">
                  <select class="form-select form-select-sm" aria-label="Bulk actions">

                    <option selected="">Best Match</option>
                    <option value="Refund">Newest</option>
                    <option value="Delete">Price</option>

                  </select>
                </div>
              </form>
            </div>
            <div class="col-auto pe-0"><a class="text-600 px-1" href="../../../app/e-commerce/product/product-grid.html"
                                          data-bs-toggle="tooltip" title="Product Grid"><span class="fas fa-th"></span></a></div>
          </div>
        </div>
      </div>
    </div>
</div>

<div class="card">

<div class="card-body p-0 overflow-hidden">
  <div class="row g-0">
      {% for product in page_obj %}
      <div class="col-12 p-card bg-100">
      <div class="row">
        <div class="col-sm-5 col-md-4">
          <div class="position-relative h-sm-100">
            <div class="swiper-container theme-slider h-100" data-swiper='{"autoplay":true,"autoHeight":true,"spaceBetween":5,"loop":true,"loopedSlides":5,"navigation":{"nextEl":".swiper-button-next","prevEl":".swiper-button-prev"}}'>
              <div class="swiper-wrapper h-100">
                <div class="swiper-slide h-100"><a class="d-block h-sm-100" href="{% url 'ecommerce:product-detail' product.slug %}">
                    <img class="rounded-1 h-100 w-100 fit-cover" src="{{ product.get_absolute_url }}" alt="" /></a></div>

              </div>
              <div class="swiper-nav">
                <div class="swiper-button-next swiper-button-white"></div>
                <div class="swiper-button-prev swiper-button-white"></div>
              </div>
            </div>
            <div class="badge rounded-pill bg-success position-absolute top-0 end-0 me-2 mt-2 fs--2 z-index-2">New</div>
          </div>
        </div>
        <div class="col-sm-7 col-md-8">
          <div class="row">
            <div class="col-lg-8">
              <h5 class="mt-3 mt-sm-0"><a class="text-dark fs-0 fs-lg-1" href="{% url 'ecommerce:product-detail' product.slug %}">{{ product.name }}</a></h5>
              <p class="fs--1 mb-2 mb-md-3"><a class="text-500" href="#!">{{ product.category.name }}</a></p>
              <ul class="list-unstyled d-none d-lg-block">
                  {% for product_attribute in product.product_attributes.all %}
                    <li><span class="fas fa-circle"
                              data-fa-transform="shrink-12"></span><span>{{ product_attribute.attribute_value.value }}</span></li>
                  {% endfor %}
              </ul>
            </div>
            <div class="col-lg-4 d-flex justify-content-between flex-column">
              <div>
                <h4 class="fs-1 fs-md-2 text-warning mb-0">${{ product.get_price }}</h4>
                <h5 class="fs--1 text-500 mb-0 mt-1">
                    {% if product.discount > 0 %}
                        <del>${{ product.price }} </del><span class="ms-1">-{{ product.discount }}%</span>
                    {% endif %}

                </h5>
                  <div class="fs--2 mb-3 d-inline-block text-decoration-none">
                    {% with ''|center:product.rating as range %}
                        {% for f in range %}
                          <span class="fa fa-star text-warning"></span>
<!--                          <span class="fa fa-star-half-alt text-warning star-icon"></span>-->
                        {% endfor %}
                    {% endwith %}
                    <span class="ms-1 text-600">({{ product.comments.count }})</span>
                <div class="d-none d-lg-block">
                  <p class="fs--1 mb-1">Shipping Cost: <strong>${{ product.shipping_cost }}</strong></p>
                  <p class="fs--1 mb-1">Stock: <strong class="text-{% if product.stock == 'available' %}success{% else %}danger{% endif %}">{{ product.stock }}</strong>
                  </p>
                </div>
              </div>
              <div class="mt-2"><a class="btn btn-sm btn-outline-secondary border-300 d-lg-block me-2 me-lg-0"
                                   href="{% url 'ecommerce:product-like' product.pk %}"><span
                      class="far fa-heart"></span><span class="ms-2 d-none d-md-inline-block">{{ product.likes.count }}</span>
              </a><a class="btn btn-sm btn-primary d-lg-block mt-lg-2" href="#!"><span class="fas fa-cart-plus"> </span>
                  <span class="ms-2 d-none d-md-inline-block">Add to Cart</span></a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
      {% endfor %}
  </div>
</div>


        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>

<!--<div class="card-footer border-top d-flex justify-content-center">-->
<!--  <button class="btn btn-falcon-default btn-sm me-2" type="button" disabled="disabled" data-bs-toggle="tooltip" data-bs-placement="top" title="Prev"><span class="fas fa-chevron-left"></span></button><a class="btn btn-sm btn-falcon-default text-primary me-2" href="#!">1</a><a class="btn btn-sm btn-falcon-default me-2" href="#!">2</a><a class="btn btn-sm btn-falcon-default me-2" href="#!"><span class="fas fa-ellipsis-h"></span></a><a class="btn btn-sm btn-falcon-default me-2" href="#!">35</a>-->
<!--  <button class="btn btn-falcon-default btn-sm" type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Next"><span class="fas fa-chevron-right"></span></button>-->
<!--</div>-->
</div>
{% endblock %}